@host = http://localhost:5226
GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhOTVhYjQxZS04Yjg1LTRlNzItYjgxNC0xMWFlMDBlMjY1YjIiLCJnaXZlbl9uYW1lIjoiTGludmFsIiwiZmFtaWx5X25hbWUiOiJNdWNoYXBpcmVpIiwianRpIjoiM2Y3MDQwOGYtZGRiZC00YmEwLTk3NjAtZGJlODEzMjVlYzQ3IiwiZXhwIjoxNjk1MzA4NDk4LCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.0KuQsaB1iCHZyvjw9bXghNVg6Q9_kyrcxujFLF_b7bM