@host = http://localhost:5226
POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Linval",
    "lastName":"Muchapirei",
    "email":"muchapireil@gmail.com",
    "password":"zipassword"
}

### three hashes to add multiple requests
POST {{host}}/auth/register