@host=http://localhost:5179
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxN2VhMDA1YS1kNjVkLTQ5YTUtYjZjZi05ZmFmNjIxZTNkZDIiLCJnaXZlbl9uYW1lIjoiTGludmFsIiwiZmFtaWx5X25hbWUiOiJXaHlHaXZlIiwianRpIjoiODRjODYwYmEtNzA3NS00MGJlLThkOWEtNjM4OGY0ZTk2NTc2IiwiZXhwIjoxNjk4MjQxNTU0LCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.RTBtPLwDhQX8Z81sgkCuNsrQpyBrozA3fXqCbjBsfK4
@hostId=asdf

POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Test",
    "description": "Test Description",
    "sections": [
    ]
}